/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class DnDApp {
  DnDApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData ankh = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData axe = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battered_axe = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone_knife = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_shield = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burning_meteor = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_axes = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown = IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_five = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_four = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_one = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_three = IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_two = IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeball = IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fairy_wand = IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData focused_lightning = IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear_heart = IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jigsaw_piece = IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife_fork = IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monster_skull = IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muscle_up = IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nuclear = IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData player = IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData queen_crown = IconData(0xea74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quill_ink = IconData(0xea75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round_shield = IconData(0xea87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_unfurled = IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
